# Baseline evaluation config
# additive baseline: predicts expression by summing individual perturbation effects

paths:
  model_dir: "model/scGPT"  # Still needs vocab.json
  data_dir: "../CellPerturb_VCC_Proj6/vcc_data/log1p"
  test_file: "test_lognorm.h5ad"
  train_file: "train_lognorm.h5ad"
  output_dir: "results/additive_djw"
  log_dir: "logs/baseline_djw" # 没有内容输出

model:
  pad_token: "<pad>"

inference:
  eval_batch_size: 16
  seed: 42
  control_target_gene: "non-targeting"

metrics:
  mae_top_k: 2000
