paths:
  model_dir: "model/scGPT"        # Pretrained model (zero-shot)
  data_dir: "data/processed"
  test_file: "test.h5ad"
  train_file: "train.h5ad"
  output_dir: "results/h5ad"

model:
  pad_token: "<pad>"
  pad_value: 0
  max_seq_len: 1536
  include_zero_gene: "batch-wise"

inference:
  eval_batch_size: 16
  seed: 42
  control_target_gene: "non-targeting"

metrics:
  mae_top_k: 2000